
spring:
  profiles:
    active: local
  http:
    encoding:
      charset: UTF-8

server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 30m

xss:
  type: hardcore    #all, regex, hardcore
  exclude-paths:
    - /api/xss/skip1
    - /api/xss/skip2

---
spring:
  profiles: local

---
spring:
  profiles: dev

---
spring:
  profiles: stage

---
spring:
  profiles: prd

